//
//  QwertyKeyboardView.swift
//  CodeWordBreaker
//
//  Created by Mike Jiang on 2026/1/13.
//
//  Generated by: https://gemini.google.com/app
//

import SwiftUI

struct QwertyKeyboardView: View {
    let onKeyPress: (String) -> Void

    private let rows: [[String]] = [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
        ["Z", "X", "C", "V", "B", "N", "M"],
    ]

    // 定义间距
    private let spacing: CGFloat = 6

    var body: some View {
        GeometryReader { geo in
            // 1. 计算标准按键宽度
            // 逻辑：(总宽度 - 所有间隙的宽度) / 最长一行的按键数量(10)
            let keyWidth = (geo.size.width - (spacing * 9)) / 10

            VStack(spacing: 8) {
                ForEach(rows, id: \.self) { row in
                    HStack(spacing: spacing) {
                        ForEach(row, id: \.self) { letter in
                            KeyButton(letter: letter) {
                                onKeyPress(letter)
                            }
                            // 2. 强制指定宽度，而不是用 .infinity
                            .frame(width: keyWidth)
                        }
                    }
                }
            }
            // 3. 确保整个键盘在垂直方向也是居中的（可选）
            .frame(width: geo.size.width, height: geo.size.height, alignment: .center)
        }
        .padding()
        // 保持键盘整体宽高比 (10个键宽 : 3行高 + 间隙)
        // 这个比例可以根据实际手感微调
        .aspectRatio(10.0 / 3.2, contentMode: .fit)
    }
}

struct KeyButton: View {
    let letter: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(letter)
                .font(.title3)
                .fontWeight(.semibold)
                .frame(maxWidth: .infinity, maxHeight: .infinity)  // 让文字填满按钮区域
                .background(
                    RoundedRectangle(cornerRadius: 6)
                        .fill(.gray.opacity(0.2))
                )
        }
        .buttonStyle(.plain)
        // 注意：这里的 aspectRatio(1) 可能会导致按键太高，
        // 如果想让按键保持特定比例，可以在这里加，但在外部 VStack 已经控制了整体比例，
        // 所以通常去掉内部的 aspectRatio 或者设为 fill 更好。
    }
}

#Preview("iPhone") {
    QwertyKeyboardView { print($0) }
}

#Preview("iPad", traits: .landscapeLeft) {
    QwertyKeyboardView { print($0) }
}
